<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PushNotificationRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PushNotificationRepository extends EntityRepository
{
//    public function persist($pushNotification) {
//        $this->getEntityManager()->persist($pushNotification);
//        $this->getEntityManager()->flush();
//    }
}
